### PR TITLE
OSX native feel by injecting CSS style with system-specific interactions

### PR DESCRIPTION
**Pull request by jakubheglas**
Text bubble contents and inputs are the only one’s that can be selected
and change cursor to text. Only text links have pointer cursor. Should be
similar to how Messages.app behaves.

### CODE REVIEW

**Comment by jakubheglas** [comment]
That css file would be great base for re-styling the app to feel more at home on osx :)

**Comment by rsms** [comment]
Interesting. I recommend moving this out of the native code and into the main.js file which is much easier to iterate and do small fixes to as it doesn't require building, signing and releasing new app builds.

**Comment by jakubheglas** [comment]
Done.

**Comment by aa-io** [comment]
Also a translucent sidebar (like messages) would be really neat, and the OS X web view does support it (as long as you inject css that wipes out the white background for certain elements)

**Comment by cembaykara** [comment]
I don't know how things goes and don't wanna be that guy but, a native quick reply feature would be amazing.

**Comment by rsms** [comment]
I encourage some of you to create a fork off of this project which aims to modify the Messenger UI. It's the policy of this project to _not_ modify the UI of Messenger beyond what it necessary to be a good desktop citizen (i.e. keyboard shortcuts, display of notifications, etc)

**Pull request closed without merging**
