### PR TITLE
Reenable preferences, active friends, etc

### PR DESCRIPTION
**Pull request by davepagurek**
Addresses https://github.com/rsms/fb-mac-messenger/issues/308, which is the base cause for https://github.com/rsms/fb-mac-messenger/issues/313, https://github.com/rsms/fb-mac-messenger/issues/309, and https://github.com/rsms/fb-mac-messenger/issues/305 as well.

So, here is what's changed on Facebook's side:
1. The left-side header is no longer its own React component
2. The gear menu itself is no longer its own React component

This means we can't easily grab the settings gear any more and we can't rely on calling methods directly on it. So here's what I did:
- I grab the header and gear button as regular DOM elements rather than React components
- I use CSS to hide the gear and back buttons since we can't rely on proxying `componentDidMount` any more, given that we don't have a component
- Digging through the messenger.com source, it looks like they switch sidebar views with `require('MessengerActions').changeMasterView(require('MessengerView').MASTER.RECENT)` and similar calls, so I use that
- Logging out and opening preferences are slightly more complicated since they require passing a React component argument into methods to attach the modal window onto a view, which is a little sketchy to try to replicate. Since preferences and logout are the first and last menu items respectively, it seems _relatively_ safe to try to click on those through the menu DOM.
  - Interesting side note about that: there still are methods attached to the menu that we could try to call directly, but they have names like `component.$MessengerSettingsMenu1()` (where, weirdly, they count from 1 to 11 but skip 6 and 10), so I figured these are not the sorts of methods we should rely on
  - Also, when going to the active friends menu and then returning to the inbox, Messenger leaves the old menu `ul` hidden in the DOM. If you open the menu, it creates a new one. If you go back and forth, it keeps adding more menus. So, when doing a DOM query to find the preferences and logout buttons, I do a `querySelectorAll` and grab the last one in order to make sure I get the most recent menu that has actual event listeners on it.

I also took the opportunity to add active friends list and inbox links into the View menu.

Let me know if there's anything in here that feels too sketchy or needs to be cleaned up!

### CODE REVIEW

**Comment by mcardillo55** [comment]
Works good for me! Thank you, this has been driving me crazy!

**Comment by chenglou** [comment]
pinging @rsms 

I work on messenger.com and use this wrapper. Because of the way assets are bundled you can't target class names easily. Things like the gear broke like five times now. Unfortunately we can't take into consideration every wrapper out there, sorry about that.

However. would it be easier for you if we exposed e.g. two or three never-changing classNames on relevant DOM elements? While we're at it, what other functionality do you need? For instance, `cmd-f` is also broken now.

**Comment by cvx** [comment]
@davepagurek Great work! 😃  One small issue though: `showActiveFriends` doesn't work while in "Message Requests" view. You'll have to change view to "master.recent" before switching to 'master.people', i.e. 

```
showActiveFriends: function() {
  require('MessengerActions').changeMasterView(require('MessengerView').MASTER.RECENT);
  require('MessengerActions').changeMasterView(require('MessengerView').MASTER.PEOPLE);
},
```

Plus, how about key shortcuts? E.g. option+cmd+{1, 2, 3} for Inbox, Requests, and Active Friends respectively?

@chenglou Thank you for coming forward, it's greatly appreciated! The best way would probably be to expose an API that would perform most common interactions that these wrappers do like showing and hiding settings window, hiding the cog icon, focusing search field, changing views (new message, requests, active friends, inbox), etc.
While that solution puts most of the maintenance burden on FB/Messenger.com team it is the least likely to accidentally break wrapper apps.

On my experimental branch I open Messenger settings with:

```
require('MessengerActions').showDialog(
  require('MessengerSettingsDialog.react'),
  { viewer: require('CurrentUser').getID() }
);
```

A wrapper-friendly API could simplify that particular action to, for example:

```
require('WrapperAPI').showDialog('settings');
```

I assume that if Facebook was eventually release its own desktop app it would probably use similar API to encapsulate all binding points between app shell and react app.

**Comment by davepagurek** [comment]
Update: added keyboard shortcuts and fixed a small CSS thing that broke with the settings gear when you hover over a conversation in small screen mode, plus the `showActiveFriends` fix from @CvX.

**Comment by rsms** [comment]
Nice work. Thanks!

**Comment by rsms** [comment]
Shipped in version 0.1.12

**Pull request merged**
