### PR TITLE
Make window move to active space upon alt-tab, instead of switching spaces.

### PR DESCRIPTION
**Pull request by mattbroussard**
This makes it much faster to send off quick messages and get back to what you were doing because:
1. You don't have to wait for the Spaces animation if the window is in a different space.
2. Alt-tabbing again brings you back to the same window you came from (as opposed to previously, where you might end up in a different window of the same app that happens to be in the space where Messenger is... or, if this doesn't happen and a space switch occurs, you have to wait on the animation again).

### CODE REVIEW

**Comment by rschmukler** [comment]
Personally I like it as it is now, which is more consistent with how the OS X "Messages" app behaves. Any chance that this could be a preference instead of a default?

**Comment by neerajbaid** [comment]
+1 for making it an option

**Comment by rsms** [comment]
I'd recommend something like this:

``` mm
  if ([[NSUserDefaults standardUserDefaults] boolForKey:@"moves-with-active-space"]) {
    _window.collectionBehavior |= NSWindowCollectionBehaviorMoveToActiveSpace;
  }
```

Then power-users can `defaults write` to change the behaviour.

Note that since this PR was created, the app now sets the FullscreenPrimary flag to collectionBehavior, so you'll need to merge the flag, rather than set it.

**Comment by mattbroussard** [comment]
Sounds reasonable, will update the PR. If at some point there are enough configurable options to merit a Preferences dialog, this should probably go there.

**Pull request merged**
