### PR TITLE
Disable right-click in WebView

### PR DESCRIPTION
**Pull request by LouisBrunner**

### CODE REVIEW

**Comment by rsms** [comment]
Why?

**Comment by LouisBrunner** [comment]
It's not really useful outside of debug.

**Comment by rsms** [comment]
"Copy link" can be pretty useful. Or any number of the other options available

screenshot 2015-04-13 18 01 01

**Comment by LouisBrunner** [comment]
Oh yeah, you are right. I couldn't trigger anything useful in the conversation frame so I thought it wasn't needed.

**Pull request closed without merging**
