### PR TITLE
Add Paste Image Support

### PR DESCRIPTION
**Pull request by b3ll**
Since WebView is weird and doesn't support pasting image data directly (the javascript file dataTransfer event is blank), and you can't really fake a dataTransfer event, one would try pasting an image but it wouldn't do anything.

However, since the fact that drag + drop does work (yay!), we can synthesize a fake drag + drop session anytime someone attempts to paste an image. If the image is on the local filesystem it'll just upload whatever it's given, but if it's clipboard data, it'll convert it to PNG and then upload that.

If the pasteboard just contains text (or anything other than an image), original pasting functionality is performed.

Yay for fake drag + drop!

### CODE REVIEW

**Comment by b3ll** [comment]
friendly ping :D

**Comment by grEvenX** [comment]
+1

**Comment by rsms** [comment]
I haven't gotten around to trying this diff out yet, but in the meantime here's a link to a similar diff referenced in #109: https://github.com/danielbuechele/goofy/pull/55

**Comment by grEvenX** [comment]
This functionality seems to already have been merged, so I'd propose to close this one

**Comment by rsms** [comment]
Nice hack!

**Comment by rsms** [comment]
Closes #109

**Comment by rsms** [comment]
Released in 0.1.3

**Pull request merged**
